tup = (0,1,2,3,2,3,1,3,2)
print("numbers: ", tup)
res = tup.count(3)
print(res)
print("first num. : ", tup[0])
print("index: ", tup.index(3))
print("length: ", len(tup))
new_tup= tup+(40,50)
print("concatenation: ", new_tup)
